name: Change Request
description: Request a configuration change, upgrade, or modification
title: "[CHANGE] "
labels: ["change-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Change Request
        Please fill out the following information to submit a change request.

  - type: input
    id: system
    attributes:
      label: System/Application
      description: What system or application is this for? (pre-filled with this repo, edit if different)
      placeholder: "e.g., Firewall, Server, Network, Web App"
      value: "enhanced-people"
    validations:
      required: true

  - type: input
    id: requested-by
    attributes:
      label: Requested By
      description: Who is requesting this change?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What change is being requested?
      placeholder: Describe the change in detail
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Business Justification
      description: Why is this change needed?
      placeholder: Explain the business need for this change
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Specific configuration changes, settings, etc.
      placeholder: Include any relevant technical specifications

  - type: dropdown
    id: downtime
    attributes:
      label: Downtime Required
      options:
        - "No"
        - "Yes"
        - "Unknown"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: Estimated Duration
      description: How long will this change take?
      placeholder: "e.g., 30 minutes, 2 hours"

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
      description: How to revert if something goes wrong
      placeholder: Describe the steps to undo this change

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: How will we verify the change was successful?
      placeholder: |
        - [ ] Test step 1
        - [ ] Test step 2

  - type: checkboxes
    id: approval
    attributes:
      label: Approval Status
      options:
        - label: Client Approved
        - label: Technical Review Complete
