name: Incident Report
description: Report an outage, service degradation, or security incident
title: "[INCIDENT] "
labels: ["incident"]
body:
  - type: markdown
    attributes:
      value: |
        ## Incident Report
        Please provide as much detail as possible about the incident.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this incident?
      options:
        - Critical - Complete outage
        - High - Major service degradation
        - Medium - Partial impact
        - Low - Minor issue
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: Affected System/Application
      description: What is affected? (pre-filled with this repo, edit if different)
      placeholder: "e.g., Email, Internet, VPN, Web App"
      value: "enhanced-people"
    validations:
      required: true

  - type: input
    id: first-reported
    attributes:
      label: Time First Reported
      description: When was the issue first reported?
      placeholder: "e.g., 2024-01-15 09:30 AM"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What is the impact?
      placeholder: Describe the incident in detail
    validations:
      required: true

  - type: textarea
    id: affected-users
    attributes:
      label: Affected Users/Services
      description: Who or what is impacted?
      placeholder: |
        - User/Service 1
        - User/Service 2

  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps Taken
      description: What has been tried so far?
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2

  - type: textarea
    id: resolution
    attributes:
      label: Resolution
      description: How was the issue resolved? (Leave blank until resolved)

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause
      description: What caused the incident? (Leave blank until post-mortem)

  - type: textarea
    id: followup
    attributes:
      label: Follow-up Actions
      description: What needs to be done to prevent recurrence?
      placeholder: |
        - [ ] Action item 1
        - [ ] Action item 2
