name: Scheduled Maintenance
description: Plan and track scheduled maintenance activities
title: "[MAINTENANCE] "
labels: ["maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        ## Scheduled Maintenance
        Use this template to plan and document scheduled maintenance activities.

  - type: input
    id: system
    attributes:
      label: System/Application
      description: What will be affected? (pre-filled with this repo, edit if different)
      placeholder: "e.g., Firewall, Server, Web App"
      value: "enhanced-people"
    validations:
      required: true

  - type: input
    id: scheduled-date
    attributes:
      label: Scheduled Date/Time
      description: When is the maintenance scheduled?
      placeholder: "e.g., 2024-01-20 10:00 PM"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: Expected Duration
      description: How long will the maintenance take?
      placeholder: "e.g., 2 hours"
    validations:
      required: true

  - type: checkboxes
    id: maintenance-type
    attributes:
      label: Maintenance Type
      description: What type of maintenance is this?
      options:
        - label: Updates/Patches
        - label: Hardware replacement
        - label: Configuration change
        - label: Backup/Recovery test
        - label: Certificate renewal
        - label: License renewal
        - label: Other

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What maintenance will be performed?
      placeholder: Describe the maintenance activities
    validations:
      required: true

  - type: dropdown
    id: downtime
    attributes:
      label: Downtime Expected
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: services-affected
    attributes:
      label: Services Affected
      description: What services will be impacted?
      placeholder: "e.g., Email, VPN, Internet"

  - type: checkboxes
    id: pre-maintenance
    attributes:
      label: Pre-Maintenance Checklist
      options:
        - label: Client notified
        - label: Backup verified
        - label: Maintenance window confirmed
        - label: Rollback plan documented

  - type: textarea
    id: procedure
    attributes:
      label: Procedure
      description: Step-by-step maintenance procedure
      placeholder: |
        1. Step one
        2. Step two
        3. Step three

  - type: checkboxes
    id: post-maintenance
    attributes:
      label: Post-Maintenance Verification
      options:
        - label: Services restored
        - label: Functionality tested
        - label: Documentation updated
        - label: Client notified of completion

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Results, issues encountered, follow-up needed
