name: New System/Device
description: Document a new computer, server, network device, or service
title: "[NEW] "
labels: ["new-system"]
body:
  - type: markdown
    attributes:
      value: |
        ## New System/Device Documentation
        Use this template to document new hardware or services being added to the environment.

  - type: dropdown
    id: type
    attributes:
      label: System Type
      options:
        - Workstation
        - Server
        - Network Device
        - Cloud Service
        - Other
    validations:
      required: true

  - type: input
    id: hostname
    attributes:
      label: Hostname
      placeholder: "e.g., WS-OFFICE-001"
    validations:
      required: true

  - type: input
    id: ip-address
    attributes:
      label: IP Address
      placeholder: "e.g., 192.168.1.100"

  - type: input
    id: mac-address
    attributes:
      label: MAC Address
      placeholder: "e.g., AA:BB:CC:DD:EE:FF"

  - type: input
    id: model
    attributes:
      label: Model/Make
      placeholder: "e.g., Dell OptiPlex 7090"

  - type: input
    id: serial
    attributes:
      label: Serial Number

  - type: input
    id: os
    attributes:
      label: OS/Firmware
      placeholder: "e.g., Windows 11 Pro"

  - type: input
    id: location
    attributes:
      label: Physical Location
      placeholder: "e.g., Server Room, Rack 1"

  - type: input
    id: assigned-user
    attributes:
      label: Assigned User
      placeholder: "e.g., John Smith"

  - type: checkboxes
    id: network-config
    attributes:
      label: Network Configuration
      options:
        - label: IP assigned (static/DHCP reservation)
        - label: Added to correct VLAN
        - label: DNS entry created
        - label: Firewall rules configured

  - type: checkboxes
    id: security-config
    attributes:
      label: Security Configuration
      options:
        - label: Local admin password set and stored
        - label: Domain joined (if applicable)
        - label: Antivirus installed
        - label: Updates applied
        - label: Backup configured

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation
      options:
        - label: Added to inventory spreadsheet/system
        - label: Credentials stored in password manager
        - label: Site documentation updated

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any special configuration, software installed, etc.
